[project]
name = "public-opinion-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "jieba>=0.42.1",
    "openai>=1.99.1",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
