[project]
name = "transformers-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sentencepiece>=0.2.1",
    "tokenizers>=0.21.4",
    "transformers>=4.55.1",
]
