[project]
name = "oauth-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pymongo>=4.13.2",
    "python-jose>=3.5.0",
    "requests-oauthlib>=2.0.0",
]
